/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_CONFDIR "/usr/local/etc/qemu"
#define CONFIG_QEMU_DATADIR "/usr/local/share/qemu"
#define CONFIG_QEMU_DOCDIR "/usr/local/share/doc/qemu"
#define CONFIG_QEMU_MODDIR "/usr/local/lib/qemu"
#define CONFIG_QEMU_LOCALSTATEDIR "/usr/local/var"
#define CONFIG_QEMU_HELPERDIR "/usr/local/libexec"
#define CONFIG_QEMU_LOCALEDIR "/usr/local/share/locale"
#define HOST_X86_64 1
#define CONFIG_DEBUG_TCG 1
#define CONFIG_POSIX 1
#define CONFIG_SLIRP 1
#define CONFIG_SMBD_COMMAND "/usr/sbin/smbd"
#define CONFIG_NETMAP 1
#define CONFIG_AUDIO_DRIVERS \

#define CONFIG_BDRV_RW_WHITELIST\
    NULL
#define CONFIG_BDRV_RO_WHITELIST\
    NULL
#define CONFIG_FNMATCH 1
#define QEMU_VERSION "2.3.0"
#define QEMU_PKGVERSION ""
#define CONFIG_PIPE2 1
#define CONFIG_ACCEPT4 1
#define CONFIG_POSIX_FALLOCATE 1
#define CONFIG_DUP3 1
#define CONFIG_PPOLL 1
#define CONFIG_IOVEC 1
#define CONFIG_PREADV 1
#define CONFIG_MADVISE 1
#define CONFIG_POSIX_MADVISE 1
#define CONFIG_BSD 1
#define CONFIG_ZERO_MALLOC 1
#define CONFIG_QOM_CAST_DEBUG 1
#define CONFIG_COROUTINE_BACKEND ucontext
#define CONFIG_COROUTINE_POOL 1
#define CONFIG_CPUID_H 1
#define CONFIG_INT128 1
#define CONFIG_TRACE_STDERR 1
#define CONFIG_TRACE_FILE trace
#define CONFIG_IASL iasl
#define HOST_DSOSUF ".so"
