#include "system.h"

#define	MIPS_XKPHYS_UNCACHED_BASE	0x80000000
#define	MIPS_XKPHYS_CACHED_NC_BASE	0x00000000

#define	MIPS_PHYS_TO_CACHED(phys)	((phys) | MIPS_XKPHYS_CACHED_NC_BASE)
#define	MIPS_PHYS_TO_UNCACHED(phys)	((phys) | MIPS_XKPHYS_UNCACHED_BASE)

#define	CHERI_JTAG_UART_BASE		JTAG_UART_0_BASE
#define	CHERI_COUNT			TIMER_0_BASE
#define	CHERI_LEDS			0x7f006000

// BERI clock frequency
#define CLOCKS_PER_SEC 100000000LL
